### ISSUE TITLE
A test case

### ISSUE THREAD

**Issue by espinielli** [ropenscilabs/parzer#2]
From https://skyvector.com/airport/EIDW/Dublin-Airport

N53°25.28' / W6°16.20'

Maybe of interest 😜

**Comment by sckott** [comment]
I get

```r
parse_lat_lon("N53°25.28'", "W6°16.20'")
#>        lat   lon
#> 1 53.42133 -6.27
```

does that look right?

**Comment by espinielli** [comment]
Correct!
